export const jobList = [
  {
    id: 1,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list1.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 2,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list2.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 3,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list3.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 4,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list4.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 5,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list1.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 6,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list2.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 7,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list3.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
  {
    id: 8,
    name: "Digital Marketer",
    logo: "assets/img/icon/job-list4.png",
    agency: "Creative Agency",
    location: "Athens,Greece",
    salaryRange: "$3500 - $4000",
    posted: "7 hours ago",
  },
];
